sudo: false
language: elixir
git:
  quiet: true
  depth: 3
elixir:
  - 1.7
  - 1.8
otp_release:
  - 21.0
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
before_script:  
  - mix do deps.get, compile --warnings-as-errors
script:
  - mix coveralls.json